options:
  auto-update: true
  ignore-outdated-warning: false
  test: false
  clear-old-config: false

StarShardsSword:
  help: '#####为星陨裁决配置信息#####'
  StarShards_Atk_Add: 1314.0
  #基础攻击力加成 默认:1314.0
  StarShards_Atk_Mult: 6.18
  #基础攻击力乘区 默认:6.18   +618%
  StarShards_AtkSpeed: 20.0
  #攻击速度 默认:20.0 +2000%
  StarShards_Health_Add: 1314.0
  #基础生命值加成 默认:1314.0
  StarShards_Health_Mult: 6.18
  #基础生命值乘区 默认:6.18   +618%
  StarShards_MoveSpeed: 0.618
  #移动速度 默认:0.618 +61.8%
  StarShards_Armor: 200.0
  #护甲 默认:200.0
  StarShards_Toughness: 200.0
  #护甲韧性 默认:200.0
  StarShards_FlySpeed: 13.14
  #飞行速度 默认:13.14 +131.4%



qwen-help:
  help: '#####这个qwen-help为配置提示，请勿删除，删除也没啥影响'
  cooldown: '#####玩家询问ai间隔时间,默认为3秒'
  api-key: '#####api-key输入阿里云百炼控制台获取的api即可，新用户可白嫖很多额度，基本够用'
  endpoint: '#####endpoint为端点，默认即可，建议默认，因为阿里云可以白嫖'
  model: '#####model为自定义模型，可选项有qwen-max、qwen3-max、qwen-plus、qwen-plus-2025-09-11等更多见官网'
  model-extra: '这里默认是回复最完善的是qwen-plus、qwen-plus-2025-09-11,回复内容也是最多的，第一个max回复内容则最为精简切最为敷衍'
  model-extra1: '其中qwen-plus为主干版本，qwen-plus-2025-09-11为快照版本，每个快照版本都有独立的免费额度'
  model-extra2: '3-max则是max的升级版，相对于max回复内容稍微详细一点'
  model-extra3: '如果想回答的精简一些，建议使用qwen-max'
  model-extra4: '在build34+版本，对所有模型的回答进行了调整，默认都为精简版本，玩家可自行对话调整字数限制'
  ai-error: '#####此处为ai回复失败反馈信息'


qwen:
  api-key: "your_api_key_here"
  endpoint: "https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation"
  model: "qwen-plus-2025-09-11"
  ai-error: "&c❌ AI响应失败，请稍后再试"
  cooldown: 3